name: Build and Release

on:
 push:
   branches:
     - main
     - "feature/*"
   tags:
     - "v*.*.*"
 pull_request:
   branches:
     - main
     - "feature/*"

jobs:
 apk:
   name: Generate APK
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Branch name
       run: echo running on branch ${GITHUB_REF##*/}
     - name: Setup JDK
       uses: actions/setup-java@v3
       with:
         distribution: temurin
         java-version: "17"
     - name: Set execution flag for gradlew
       run: chmod +x gradlew
     - name: Build APK
       run: bash ./gradlew assembleDebug --stacktrace
     - name: Upload APK
       uses: actions/upload-artifact@v1
       with:
         name: apk
         path: app/build/outputs/apk/debug/app-debug.apk

 release:
   name: Release APK
   needs: apk
   runs-on: ubuntu-latest
   steps:
     - name: Get branch name
       id: branch-name
       uses: tj-actions/branch-names@v5.1
     - name: Print branch    
       run: |
         echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"
       
     - name: Download APK from build
       uses: actions/download-artifact@v1
       with:
         name: apk
     - name: Create Release
       id: create_release
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
       with:
         tag_name: ${{ github.run_number }}
         release_name: ${{ github.event.repository.name }}  ${{ steps.branch-name.outputs.current_branch }} v${{ github.run_number }}.${{ github.run_attempt }}
     - name: Upload Release APK
       id: upload_release_asset
       uses: actions/upload-release-asset@v1.0.1
       env:
         GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: apk/app-debug.apk
         asset_name: ${{ github.event.repository.name }}  ${{ steps.branch-name.outputs.current_branch }} v${{ github.run_number }}.${{ github.run_attempt }}.apk
         asset_content_type: application/zip
     - name: Bark
       run: curl http%3A%2F%2Fpush.bark.xiaobingkj.com%2F4uMKBqxAmmRCPFUkyJLgnB%2FAndroid%E7%89%88Giteer%E5%8F%91%E5%B8%83%E6%96%B0%E7%89%88%E4%BA%86%EF%BC%81%2F%24%7B%7B%20github.event.repository.name%20%7D%7D%20%20%24%7B%7B%20steps.branch-name.outputs.current_branch%20%7D%7D%20v%24%7B%7B%20github.run_number%20%7D%7D.%24%7B%7B%20github.run_attempt%20%7D%7D.apk%3Fgroup%3DGiteerAndroid
